### ISSUE TITLE
Moving to another activity freezes application

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#8]
Sometimes (it happens to me quite a lot), when you move from one activity to another (for example, from the "Squad" list to a player's page), the app freezes for a few seconds showing a black screen while doing so. This didn't happen in previous versions of FotMob.

**Comment by cnordvik** [comment]
Thanks! We fixed the issue. Very nice testing :-)

**Comment by yonifra** [comment]
I think we should reopen this issue, since it sometimes still happen to me (although much less frequently, mainly upon application initial start-up)

**Comment by cnordvik** [comment]
We will have a more critical look at the startup time of the app. It always starts fast when I test it but I can check it some more since you have issues with it.

**Comment by cnordvik** [comment]
Closing this now, let me know if I shouldn't :-)
